<?php

declare(strict_types=1);

namespace App\Repositories;

use PDO;
use PDOStatement;
use PDOException;
use RuntimeException;

/**
 * BaseRepository
 *
 * Provides common PDO helpers shared by all concrete repositories.
 * Concrete repositories extend this class and inject the PDO connection
 * through the constructor.
 */
abstract class BaseRepository
{
    public function __construct(
        protected readonly PDO $pdo,
    ) {}

    // -------------------------------------------------------------------------
    // Query helpers
    // -------------------------------------------------------------------------

    /**
     * Prepare and execute a statement, returning the PDOStatement on success.
     *
     * @param  array<string, mixed> $params
     * @throws RuntimeException On query failure.
     */
    protected function execute(string $sql, array $params = []): PDOStatement
    {
        try {
            $stmt = $this->pdo->prepare($sql);
            $stmt->execute($params);
            return $stmt;
        } catch (PDOException $e) {
            throw new RuntimeException(
                'Database query failed: ' . $e->getMessage(),
                (int) $e->getCode(),
                $e,
            );
        }
    }

    /**
     * Execute a query and return the first row as an associative array,
     * or null when no row matches.
     *
     * @param  array<string, mixed> $params
     * @return array<string, mixed>|null
     */
    protected function fetchOne(string $sql, array $params = []): ?array
    {
        $stmt = $this->execute($sql, $params);
        $row  = $stmt->fetch(PDO::FETCH_ASSOC);
        return $row !== false ? $row : null;
    }

    /**
     * Execute a query and return all rows as an array of associative arrays.
     *
     * @param  array<string, mixed>    $params
     * @return array<int, array<string, mixed>>
     */
    protected function fetchAll(string $sql, array $params = []): array
    {
        return $this->execute($sql, $params)->fetchAll(PDO::FETCH_ASSOC);
    }

    /**
     * Execute an INSERT/UPDATE/DELETE and return the number of affected rows.
     *
     * @param  array<string, mixed> $params
     */
    protected function modify(string $sql, array $params = []): int
    {
        return $this->execute($sql, $params)->rowCount();
    }

    /**
     * Return the auto-increment ID generated by the most recent INSERT.
     */
    protected function lastInsertId(): int
    {
        return (int) $this->pdo->lastInsertId();
    }

    /**
     * Count the total rows matching the given SQL/params.
     * The SQL must return a single column named `total`.
     *
     * @param  array<string, mixed> $params
     */
    protected function count(string $sql, array $params = []): int
    {
        $row = $this->fetchOne($sql, $params);
        return isset($row['total']) ? (int) $row['total'] : 0;
    }

    // -------------------------------------------------------------------------
    // Transaction helpers
    // -------------------------------------------------------------------------

    /**
     * Execute the given callable inside a database transaction.
     * Commits on success; rolls back and re-throws on failure.
     *
     * @template T
     * @param  callable(): T $callback
     * @return T
     */
    protected function transaction(callable $callback): mixed
    {
        $this->pdo->beginTransaction();
        try {
            $result = $callback();
            $this->pdo->commit();
            return $result;
        } catch (\Throwable $e) {
            $this->pdo->rollBack();
            throw $e;
        }
    }

    // -------------------------------------------------------------------------
    // Pagination helper
    // -------------------------------------------------------------------------

    /**
     * Build a LIMIT/OFFSET clause from page + perPage values.
     *
     * @return array{limit: int, offset: int}
     */
    protected function limitOffset(int $page, int $perPage): array
    {
        $page    = max(1, $page);
        $perPage = max(1, min(500, $perPage));

        return [
            'limit'  => $perPage,
            'offset' => ($page - 1) * $perPage,
        ];
    }
}
